name: joshua charles hart
favicon: null
layout_spectrum: 0.26359
typography_spectrum: 0.15413
title: website of painter/thingmaker joshua charles hart
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e8e3'
    - '#1a1c19'
    - '#0076a8'
    - '#92af93'
    - '#804f2e'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
